### ISSUE TITLE
ID1505-Edit Item

### ISSUE THREAD

**Issue by wayuk** [tribuwayuk/gzais#124]
1   "Given that the admin/property wants to edit an item
When the admin/property clicks the edit link
Then these fields should be enabled/editable:
- Item Type 
- Item Name 
- Item Description
- Serial Number 
- Date Purchased 
- Item Supplier 
- Address of Supplier 
- Contact Number of Supplier 
- Reason for Purchase
- Status (dropdown menu)"
  2   "Given that the admin/property wants to edit an item
  When the admin/property clicks the edit option
  Then input fields should follow proper validation and limitation of text input in each field

"
3   "Given that the admin/property custodian wants to save an edited item information
When the admin clicks the save button
Then new information should be saved"
4   "Given that the admin/property custodian wants to cancel an edited item information
When the admin clicks the cancel button
Then ""Manage Assets"" list should be displayed"
5   "Given that the admin/property custodian successfully save the new item information
When the admin/property custodian selects/clicks ""View Details"" option for a specific item
Then new information should be displayed."
6   "Should created route for ""View item details""
Route: Assets/ID
"

**Comment by retrac18** [comment]
already done. . .
