### ISSUE TITLE
1513 Defect: User Management Newly added user displays NaN values in User List

### ISSUE THREAD

**Issue by wayuk** [tribuwayuk/gzais#76]
Steps to replicate:
1. Add a user with valid input. Use email xy@xy.com
2. Add another user with valid input and use the same email (xy@xy.com)
3. The newly added user values will be displayed as NaN (See screenshot)

Another step to replicate:
1. Add a user with all valid input except the date
2. Edit the date and include a letter in the date. For example: 11/12/2013 to 11/12/201A
3. The newly added user values will be displayed as NaN (See screenshot)
I think we should adjust the calendar that the textfield should be un-editable. But when the user clicks the date field, the date picker drop down should display

**Comment by penzur** [comment]
Done
