### ISSUE TITLE
ID1500 User Management View User

### ISSUE THREAD

**Issue by wayuk** [tribuwayuk/gzais#85]
1   "Given that the Admin/property custodian access the Detailed view of users

When the Admin/property custodian viewed the Detailed view of users

Then list of users should display the following information (in tabular form):
- First Name
- Middle Name
- Last Name
- Address
- Date of Birth
- Gender
- User Role
- Date Employed
- Email
- Assets
- Edit (Button)"
  2   "Given that the Admin/ Property want’s to view the assets of a specific user

When the Admin/Property views the Assets Table

Then the table should display the:
- Status
- Item Name
- Date Purchased
- Serial Number"
  3   "Given the Admin/Property Custodian want's to edit a user

When the Admin/Property Custodian clicks the edit button

Then the Edit User form should be displayed (Same as the Edit User user story)"
4   Should create user route for specific user when viewing user profile example: http://gzais.herokuapp.com/employees/ID

**Comment by technowar** [comment]
I call dibs.

**Comment by rohitdaryanani** [comment]
ok ako g assign nimo

**Comment by technowar** [comment]
Ibawi nalang kay d makuha lol

**Comment by rohitdaryanani** [comment]
lol matud pa crissy no backsis

**Comment by technowar** [comment]
Cannot bring this @elizar
